export EDITOR='lvim'
export VISUAL='lvim'
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export MANROFFOPT="-P -c"

export LANG='en_US.UTF-8'

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/{,s}bin(N)
  $HOME/.local/bin(N)
  $HOME/.config/sway/scripts(N)
  $HOME/.local/share/cargo/bin(N)
  /opt/{homebrew,local}/{,s}bin(N)
  /usr/local/go/bin(N)
  /usr/local/{,s}bin(N)
  $home/.pyenv/bin(N)
  $path
)

#
# Less
#

# Set the default Less options.
if [[ -z "$LESS" ]]; then
  export LESS='-g -i -M -R -S -w -z-4 --use-color -Dd+r$Du+b$'
fi

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if [[ -z "$LESSOPEN" ]] && (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi
