#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# xdg dir stuff
export XDG_DATA_HOME=$HOME/.local/share
export XDG_CONFIG_HOME=$HOME/.config
export XDG_STATE_HOME=$HOME/.local/state
export XDG_CACHE_HOME=$HOME/.cache

export XDG_DOCUMENTS_DIR="$HOME/docs"
export XDG_DOWNLOAD_DIR="$XDG_DOCUMENTS_DIR/downloads"
export XDG_MUSIC_DIR="$XDG_DOCUMENTS_DIR/music"
export XDG_PICTURES_DIR="$XDG_DOCUMENTS_DIR/pics"
export XDG_VIDEOS_DIR="$XDG_DOCUMENTS_DIR/vids"

export ANDROID_USER_HOME="$XDG_DATA_HOME"/android
export W3M_DIR="$XDG_DATA_HOME"/w3m
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv
export HISTFILE="$XDG_STATE_HOME"/bash/history
export GOPATH="$XDG_DATA_HOME"/go
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export XCURSOR_PATH=/usr/share/icons:$XDG_DATA_HOME/icons
export NVM_DIR="$XDG_DATA_HOME"/nvm
export RANGER_LOAD_DEFAULT_RC=FALSE
export GRIM_DEFAULT_DIR="$HOME"/pics/screens
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/

# Zoxide vars
export _ZO_DATA_DIR=$XDG_DATA_HOME/zoxide
export _ZO_ECHO=1
export _ZO_RESOLVE_SYMLINKS=1


