#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
#
alias sensii="TERM=xterm kitten ${sshSecret}"
## Config aliases
alias swayconf="${EDITOR} ~/.config/sway/config"
alias kittyconf="${EDITOR} ~/.config/kitty/kitty.conf"
alias barconf="ranger ~/.config/sway/bars/"

## cd aliases
alias bins="cd ~/.local/bin/"
alias wmd="cd ~/.config/sway/"

## cmds
alias sctl="sudo systemctl"
alias vpn="mullvad"
alias smarts="smartthings"
alias fetch="fastfetch --config ~/.config/fastfetch/hw-sw-info.jsonc"
alias ls="eza"
alias dmesg="dmesg --color=always"
alias reflect-mirrors="sudo reflector --save /etc/pacman.d/mirrorlist --sort rate --protocol https --age 12 --latest 10 -c DE,SE,DK,NO,NL"
alias wget=wget --hsts-file="$XDG_DATA_HOME/wget-hsts"
alias adb='HOME="$XDG_DATA_HOME"/android adb'
alias obs="obs --enable-features=WebRTCPipeWireCapturer"
alias btctl="bluetoothctl"
