#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
#
alias dotfiles='/usr/bin/git --git-dir="$HOME/.dotfiles/" --work-tree="$HOME"'
## Config aliases

## cd aliases

## cmds
alias sctl="sudo systemctl"
alias uctö "systemctl --user"
alias smarts="smartthings"
alias fetch="fastfetch --config ~/.config/fastfetch/hw-sw-info.jsonc"
alias ls="eza --group--directories-first"
alias reflect-mirrors="sudo reflector --save /etc/pacman.d/mirrorlist --sort rate --protocol https --age 12 --latest 10 -c DE,SE,DK,NO,NL"
alias dmesg="dmesg --color=always"
alias wget="wget --hsts-file=$XDG_DATA_HOME/wget-hsts"
alias bootlog="sudo journalctl -b | grep -v warp | less"
alias tree="tree --dirsfirst -C -L 3"
alias ubad="curl -Fsecret= u-b.ad -F"



